### ISSUE TITLE
Please change the name.....

### ISSUE THREAD

**Issue by RedSpeeds** [Mrdabup/ShockingCompany#5]
Hey have made an mod that does the exact same thing as mine does however with less functionality and its been causing issues where people have been messaging me about problems about your mod thinking they had installed mine so i ask you to please change the name of the mod on the thunderstore.

Kind regards,
Red

**Comment by Mrdabup** [comment]
Hello! For what I understand, you can't change names in thunderstore. I understand the issue you are talking about. We can change the repo name and edit the description for the new name. If you know how to change mod names in thunderstore, please let us know.

Due regards,
Mrdabup

**Comment by Mrdabup** [comment]
Package has been moved and named something else, thank you for giving us some awareness with this. If any more issues arrise, please let us know!

Have a good evening/ day!
Mrdabup
